export const technicalDebtRegistry = {
  releaseReadinessEvidence: {
    rlsPoliciesDrafted: {
      complete: true,
      sourceHints: ['supabase/rls_*.sql', 'supabase/migrations/*_rls.sql'],
    },
    storagePlanCreated: {
      complete: true,
      sourceHints: ['supabase/README.md', 'supabase/migrations/20260628_enable_project_photos_storage_beta.sql'],
    },
    productionDeployment: {
      sourceHint: 'docs/PRIVATE_BETA_LAUNCH_CHECKLIST.md#production-deployment-readiness',
      verifiedAt: '2026-08-15T21:40:10-04:00',
      verificationChecks: [
        { id: 'siteDomain', labelKey: 'releaseCheckSiteDomain', status: 'PASS', evidenceKey: 'releaseEvidenceSiteDomain' },
        { id: 'appDomain', labelKey: 'releaseCheckAppDomain', status: 'PASS', evidenceKey: 'releaseEvidenceAppDomain' },
        { id: 'portalDomain', labelKey: 'releaseCheckPortalDomain', status: 'PASS', evidenceKey: 'releaseEvidencePortalDomain' },
        { id: 'authDomain', labelKey: 'releaseCheckAuthDomain', status: 'PASS', evidenceKey: 'releaseEvidenceAuthDomain' },
        { id: 'https', labelKey: 'releaseCheckHttps', status: 'PASS', evidenceKey: 'releaseEvidenceHttps' },
        { id: 'spaRouting', labelKey: 'releaseCheckSpaRouting', status: 'PASS', evidenceKey: 'releaseEvidenceSpaRouting' },
        { id: 'authRedirects', labelKey: 'releaseCheckAuthRedirects', status: 'PENDING', evidenceKey: 'releaseEvidenceAuthRedirects' },
        { id: 'databaseMigrations', labelKey: 'releaseCheckDatabaseMigrations', status: 'PENDING', evidenceKey: 'releaseEvidenceDatabaseMigrations' },
        { id: 'rls', labelKey: 'releaseCheckRls', status: 'PENDING', evidenceKey: 'releaseEvidenceRls' },
        { id: 'edgeFunction', labelKey: 'releaseCheckEdgeFunction', status: 'PENDING', evidenceKey: 'releaseEvidenceEdgeFunction' },
        { id: 'portalIsolation', labelKey: 'releaseCheckPortalIsolation', status: 'PENDING', evidenceKey: 'releaseEvidencePortalIsolation' },
        { id: 'productionEnvironment', labelKey: 'releaseCheckProductionEnvironment', status: 'PASS', evidenceKey: 'releaseEvidenceProductionEnvironment' },
        { id: 'developerRoutes', labelKey: 'releaseCheckDeveloperRoutes', status: 'PASS', evidenceKey: 'releaseEvidenceDeveloperRoutes' },
      ],
    },
  },
  todoItems: [
    {
      id: 'clientEstimateApproval',
      titleKey: 'technicalDebtEstimateApprovalTitle',
      descriptionKey: 'technicalDebtEstimateApprovalDescription',
      severity: 'medium',
      affectedAreaKey: 'technicalDebtAreaEstimateSharing',
      nextActionKey: 'technicalDebtEstimateApprovalNextAction',
      classification: 'backlog',
      whyItMattersKey: 'technicalDebtEstimateApprovalWhy',
      priority: 'high',
      dependencyKeys: [
        'technicalDebtDependencyPublicMutationSecurity',
        'technicalDebtDependencyEstimateLifecycle',
        'technicalDebtDependencyContractorNotifications',
        'technicalDebtDependencyApprovalMeaning',
      ],
      futureSprintAreaKey: 'technicalDebtSprintEstimateAcceptance',
      sourceHint: 'developerHealthRegistry.todoItems.clientEstimateApproval',
    },
    {
      id: 'contractorConfigurableServices',
      titleKey: 'technicalDebtConfigurableServicesTitle',
      descriptionKey: 'technicalDebtConfigurableServicesDescription',
      severity: 'low',
      affectedAreaKey: 'technicalDebtAreaProjectSetup',
      nextActionKey: 'technicalDebtConfigurableServicesNextAction',
      classification: 'backlog',
      whyItMattersKey: 'technicalDebtConfigurableServicesWhy',
      priority: 'medium',
      dependencyKeys: ['technicalDebtDependencyServiceSettings', 'technicalDebtDependencyServiceDataModel'],
      futureSprintAreaKey: 'technicalDebtSprintServiceConfiguration',
      sourceHint: 'JobFormModal.projectTypes',
    },
    {
      id: 'portalClientMessaging',
      titleKey: 'technicalDebtPortalMessagingTitle',
      descriptionKey: 'technicalDebtPortalMessagingDescription',
      severity: 'medium',
      affectedAreaKey: 'technicalDebtAreaClientPortal',
      nextActionKey: 'technicalDebtPortalMessagingNextAction',
      classification: 'backlog',
      whyItMattersKey: 'technicalDebtPortalMessagingWhy',
      priority: 'medium',
      dependencyKeys: ['technicalDebtDependencyMessagingProvider', 'technicalDebtDependencyConsentRules'],
      futureSprintAreaKey: 'technicalDebtSprintClientCommunication',
      sourceHint: 'developerHealthRegistry.todoItems',
    },
  ],
  comingSoonPages: [
    {
      id: 'paymentsPage',
      titleKey: 'technicalDebtPaymentsPageTitle',
      descriptionKey: 'technicalDebtPaymentsPageDescription',
      severity: 'medium',
      affectedAreaKey: 'payments',
      nextActionKey: 'technicalDebtPaymentsPageNextAction',
      classification: 'backlog',
      whyItMattersKey: 'technicalDebtPaymentsPageWhy',
      priority: 'medium',
      dependencyKeys: ['technicalDebtDependencyPaymentWorkspace', 'technicalDebtDependencyPaymentPermissions'],
      futureSprintAreaKey: 'technicalDebtSprintPaymentsWorkspace',
      sourceHint: 'developerHealthRegistry.comingSoonPages',
    },
  ],
}
